# Generated by Django 5.0.7 on 2024-07-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_parcel_post_machine_locker'),
        ('post_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='post_machine_recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='post_machine.postmachine'),
        ),
    ]
