# Generated by Django 5.0.7 on 2024-07-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0003_alter_parcel_post_machine_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='post_machine_recipient',
        ),
    ]
