# Generated by Django 5.0.7 on 2024-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0004_remove_parcel_post_machine_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='open_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
