# Generated by Django 5.0.7 on 2024-07-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_alter_parcel_open_date_time'),
        ('post_machine', '0002_alter_locker_post_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='open_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='post_machine_locker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='post_machine.locker'),
        ),
    ]
