# Generated by Django 5.0.7 on 2024-07-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='post_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lockers', to='post_machine.postmachine'),
        ),
    ]
